
import java.util.ArrayList;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lamsz
 */
public class MonopolyViewds extends javax.swing.JFrame {

    /**
     * Creates new form MonopolyView
     */    
    public ArrayList<JLabel> slotLabels  = new ArrayList<JLabel>();
    //public {}
    
    public MonopolyView() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabbedPane = new javax.swing.JTabbedPane();
        gamePanel = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        slot0Panel = new javax.swing.JPanel();
        nameLabel0 = new javax.swing.JLabel();
        spaceLabel0 = new javax.swing.JLabel();
        priceLabel0 = new javax.swing.JLabel();
        ownerLabel0 = new javax.swing.JLabel();
        slot22Panel = new javax.swing.JPanel();
        nameLabel22 = new javax.swing.JLabel();
        spaceLabel22 = new javax.swing.JLabel();
        priceLabel22 = new javax.swing.JLabel();
        ownerLabel22 = new javax.swing.JLabel();
        slot1Panel = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        spaceLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        ownerLabel1 = new javax.swing.JLabel();
        slot21Panel = new javax.swing.JPanel();
        nameLabel21 = new javax.swing.JLabel();
        spaceLabel21 = new javax.swing.JLabel();
        priceLabel21 = new javax.swing.JLabel();
        ownerLabel21 = new javax.swing.JLabel();
        slot20Panel = new javax.swing.JPanel();
        nameLabel20 = new javax.swing.JLabel();
        spaceLabel20 = new javax.swing.JLabel();
        priceLabel20 = new javax.swing.JLabel();
        ownerLabel20 = new javax.swing.JLabel();
        slot19Panel = new javax.swing.JPanel();
        nameLabel19 = new javax.swing.JLabel();
        spaceLabel19 = new javax.swing.JLabel();
        priceLabel19 = new javax.swing.JLabel();
        ownerLabel19 = new javax.swing.JLabel();
        slot10Panel = new javax.swing.JPanel();
        nameLabel10 = new javax.swing.JLabel();
        spaceLabel10 = new javax.swing.JLabel();
        priceLabel10 = new javax.swing.JLabel();
        ownerLabel10 = new javax.swing.JLabel();
        slot9Panel = new javax.swing.JPanel();
        nameLabel9 = new javax.swing.JLabel();
        spaceLabel9 = new javax.swing.JLabel();
        priceLabel9 = new javax.swing.JLabel();
        ownerLabel9 = new javax.swing.JLabel();
        slot8Panel = new javax.swing.JPanel();
        nameLabel8 = new javax.swing.JLabel();
        spaceLabel8 = new javax.swing.JLabel();
        priceLabel8 = new javax.swing.JLabel();
        ownerLabel8 = new javax.swing.JLabel();
        slot18Panel = new javax.swing.JPanel();
        nameLabel18 = new javax.swing.JLabel();
        spaceLabel18 = new javax.swing.JLabel();
        priceLabel18 = new javax.swing.JLabel();
        ownerLabel18 = new javax.swing.JLabel();
        slot17Panel = new javax.swing.JPanel();
        nameLabel17 = new javax.swing.JLabel();
        spaceLabel17 = new javax.swing.JLabel();
        priceLabel17 = new javax.swing.JLabel();
        ownerLabel17 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        slot13Panel = new javax.swing.JPanel();
        nameLabel13 = new javax.swing.JLabel();
        spaceLabel13 = new javax.swing.JLabel();
        priceLabel13 = new javax.swing.JLabel();
        ownerLabel13 = new javax.swing.JLabel();
        slot12Panel = new javax.swing.JPanel();
        nameLabel12 = new javax.swing.JLabel();
        spaceLabel12 = new javax.swing.JLabel();
        priceLabel12 = new javax.swing.JLabel();
        ownerLabel12 = new javax.swing.JLabel();
        slot11Panel = new javax.swing.JPanel();
        nameLabel11 = new javax.swing.JLabel();
        spaceLabel11 = new javax.swing.JLabel();
        priceLabel11 = new javax.swing.JLabel();
        ownerLabel11 = new javax.swing.JLabel();
        slot16Panel = new javax.swing.JPanel();
        nameLabel16 = new javax.swing.JLabel();
        spaceLabel16 = new javax.swing.JLabel();
        priceLabel16 = new javax.swing.JLabel();
        ownerLabel16 = new javax.swing.JLabel();
        slot2Panel = new javax.swing.JPanel();
        nameLabel2 = new javax.swing.JLabel();
        spaceLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        ownerLabel2 = new javax.swing.JLabel();
        slot14Panel = new javax.swing.JPanel();
        nameLabel14 = new javax.swing.JLabel();
        spaceLabel14 = new javax.swing.JLabel();
        priceLabel14 = new javax.swing.JLabel();
        ownerLabel14 = new javax.swing.JLabel();
        slot15Panel = new javax.swing.JPanel();
        nameLabel15 = new javax.swing.JLabel();
        spaceLabel15 = new javax.swing.JLabel();
        priceLabel15 = new javax.swing.JLabel();
        ownerLabel15 = new javax.swing.JLabel();
        slot3Panel = new javax.swing.JPanel();
        nameLabel3 = new javax.swing.JLabel();
        spaceLabel3 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        ownerLabel3 = new javax.swing.JLabel();
        slot4Panel = new javax.swing.JPanel();
        nameLabel4 = new javax.swing.JLabel();
        spaceLabel4 = new javax.swing.JLabel();
        priceLabel4 = new javax.swing.JLabel();
        ownerLabel4 = new javax.swing.JLabel();
        slot5Panel = new javax.swing.JPanel();
        nameLabel5 = new javax.swing.JLabel();
        spaceLabel5 = new javax.swing.JLabel();
        priceLabel5 = new javax.swing.JLabel();
        ownerLabel5 = new javax.swing.JLabel();
        slot6Panel = new javax.swing.JPanel();
        nameLabel6 = new javax.swing.JLabel();
        spaceLabel6 = new javax.swing.JLabel();
        priceLabel6 = new javax.swing.JLabel();
        ownerLabel6 = new javax.swing.JLabel();
        slot7Panel = new javax.swing.JPanel();
        nameLabel7 = new javax.swing.JLabel();
        spaceLabel7 = new javax.swing.JLabel();
        priceLabel7 = new javax.swing.JLabel();
        ownerLabel7 = new javax.swing.JLabel();
        testingPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel24.setBackground(new java.awt.Color(204, 204, 255));
        java.awt.GridBagLayout jPanel24Layout = new java.awt.GridBagLayout();
        jPanel24Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel24Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel24.setLayout(jPanel24Layout);

        slot0Panel.setMinimumSize(new java.awt.Dimension(200, 100));
        slot0Panel.setPreferredSize(new java.awt.Dimension(205, 100));

        nameLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel0.setText("nameLabel0");

        spaceLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel0.setText("spaceLabel0");

        priceLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel0.setText("priceLabel0");

        ownerLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel0.setText("ownerLabel0");

        javax.swing.GroupLayout slot0PanelLayout = new javax.swing.GroupLayout(slot0Panel);
        slot0Panel.setLayout(slot0PanelLayout);
        slot0PanelLayout.setHorizontalGroup(
            slot0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ownerLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spaceLabel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nameLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
        slot0PanelLayout.setVerticalGroup(
            slot0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot0PanelLayout.createSequentialGroup()
                .addComponent(nameLabel0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spaceLabel0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel0)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel24.add(slot0Panel, gridBagConstraints);

        slot22Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel22.setText("nameLabel22");

        spaceLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel22.setText("jLabel86");

        priceLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel22.setText("jLabel87");

        ownerLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel22.setText("jLabel88");

        javax.swing.GroupLayout slot22PanelLayout = new javax.swing.GroupLayout(slot22Panel);
        slot22Panel.setLayout(slot22PanelLayout);
        slot22PanelLayout.setHorizontalGroup(
            slot22PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot22PanelLayout.setVerticalGroup(
            slot22PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot22PanelLayout.createSequentialGroup()
                .addComponent(nameLabel22)
                .addGap(1, 1, 1)
                .addComponent(spaceLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(priceLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel22)
                .addGap(24, 24, 24))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel24.add(slot22Panel, gridBagConstraints);

        slot1Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel1.setText("nameLabel1");

        spaceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel1.setText("jLabel2");

        priceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel1.setText("jLabel3");

        ownerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel1.setText("jLabel4");

        javax.swing.GroupLayout slot1PanelLayout = new javax.swing.GroupLayout(slot1Panel);
        slot1Panel.setLayout(slot1PanelLayout);
        slot1PanelLayout.setHorizontalGroup(
            slot1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot1PanelLayout.setVerticalGroup(
            slot1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot1PanelLayout.createSequentialGroup()
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot1Panel, gridBagConstraints);

        slot21Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel21.setText("nameLabel21");

        spaceLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel21.setText("jLabel82");

        priceLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel21.setText("jLabel83");

        ownerLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel21.setText("jLabel84");

        javax.swing.GroupLayout slot21PanelLayout = new javax.swing.GroupLayout(slot21Panel);
        slot21Panel.setLayout(slot21PanelLayout);
        slot21PanelLayout.setHorizontalGroup(
            slot21PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot21PanelLayout.setVerticalGroup(
            slot21PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot21PanelLayout.createSequentialGroup()
                .addComponent(nameLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel21)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel24.add(slot21Panel, gridBagConstraints);

        slot20Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel20.setText("nameLabel20");

        spaceLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel20.setText("jLabel78");

        priceLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel20.setText("jLabel79");

        ownerLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel20.setText("jLabel80");

        javax.swing.GroupLayout slot20PanelLayout = new javax.swing.GroupLayout(slot20Panel);
        slot20Panel.setLayout(slot20PanelLayout);
        slot20PanelLayout.setHorizontalGroup(
            slot20PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot20PanelLayout.setVerticalGroup(
            slot20PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot20PanelLayout.createSequentialGroup()
                .addComponent(nameLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel20)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel24.add(slot20Panel, gridBagConstraints);

        slot19Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel19.setText("nameLabel19");

        spaceLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel19.setText("jLabel74");

        priceLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel19.setText("jLabel75");

        ownerLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel19.setText("jLabel76");

        javax.swing.GroupLayout slot19PanelLayout = new javax.swing.GroupLayout(slot19Panel);
        slot19Panel.setLayout(slot19PanelLayout);
        slot19PanelLayout.setHorizontalGroup(
            slot19PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot19PanelLayout.setVerticalGroup(
            slot19PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot19PanelLayout.createSequentialGroup()
                .addComponent(nameLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel19)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot19Panel, gridBagConstraints);

        slot10Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel10.setText("nameLabel10");

        spaceLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel10.setText("jLabel38");

        priceLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel10.setText("jLabel39");

        ownerLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel10.setText("jLabel40");

        javax.swing.GroupLayout slot10PanelLayout = new javax.swing.GroupLayout(slot10Panel);
        slot10Panel.setLayout(slot10PanelLayout);
        slot10PanelLayout.setHorizontalGroup(
            slot10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot10PanelLayout.setVerticalGroup(
            slot10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot10PanelLayout.createSequentialGroup()
                .addComponent(nameLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spaceLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel10)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 6;
        jPanel24.add(slot10Panel, gridBagConstraints);

        slot9Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel9.setText("nameLabel9");

        spaceLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel9.setText("jLabel34");

        priceLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel9.setText("jLabel35");

        ownerLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel9.setText("jLabel36");

        javax.swing.GroupLayout slot9PanelLayout = new javax.swing.GroupLayout(slot9Panel);
        slot9Panel.setLayout(slot9PanelLayout);
        slot9PanelLayout.setHorizontalGroup(
            slot9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot9PanelLayout.setVerticalGroup(
            slot9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot9PanelLayout.createSequentialGroup()
                .addComponent(nameLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel9)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 4;
        jPanel24.add(slot9Panel, gridBagConstraints);

        slot8Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel8.setText("nameLabel8");

        spaceLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel8.setText("jLabel30");

        priceLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel8.setText("jLabel31");

        ownerLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel8.setText("jLabel32");

        javax.swing.GroupLayout slot8PanelLayout = new javax.swing.GroupLayout(slot8Panel);
        slot8Panel.setLayout(slot8PanelLayout);
        slot8PanelLayout.setHorizontalGroup(
            slot8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot8PanelLayout.setVerticalGroup(
            slot8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot8PanelLayout.createSequentialGroup()
                .addComponent(nameLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spaceLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel8)
                .addGap(25, 25, 25))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        jPanel24.add(slot8Panel, gridBagConstraints);

        slot18Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel18.setText("nameLabel18");

        spaceLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel18.setText("jLabel70");

        priceLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel18.setText("jLabel71");

        ownerLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel18.setText("jLabel72");

        javax.swing.GroupLayout slot18PanelLayout = new javax.swing.GroupLayout(slot18Panel);
        slot18Panel.setLayout(slot18PanelLayout);
        slot18PanelLayout.setHorizontalGroup(
            slot18PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot18PanelLayout.setVerticalGroup(
            slot18PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot18PanelLayout.createSequentialGroup()
                .addComponent(nameLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel18)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot18Panel, gridBagConstraints);

        slot17Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel17.setText("nameLabel17");

        spaceLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel17.setText("jLabel66");

        priceLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel17.setText("jLabel67");

        ownerLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel17.setText("jLabel68");

        javax.swing.GroupLayout slot17PanelLayout = new javax.swing.GroupLayout(slot17Panel);
        slot17Panel.setLayout(slot17PanelLayout);
        slot17PanelLayout.setHorizontalGroup(
            slot17PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot17PanelLayout.setVerticalGroup(
            slot17PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot17PanelLayout.createSequentialGroup()
                .addComponent(nameLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel17)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot17Panel, gridBagConstraints);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel24.add(centerPanel, gridBagConstraints);

        slot13Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel13.setText("nameLabel13");

        spaceLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel13.setText("jLabel50");

        priceLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel13.setText("jLabel51");

        ownerLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel13.setText("jLabel52");

        javax.swing.GroupLayout slot13PanelLayout = new javax.swing.GroupLayout(slot13Panel);
        slot13Panel.setLayout(slot13PanelLayout);
        slot13PanelLayout.setHorizontalGroup(
            slot13PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot13PanelLayout.setVerticalGroup(
            slot13PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot13PanelLayout.createSequentialGroup()
                .addComponent(nameLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel13)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot13Panel, gridBagConstraints);

        slot12Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel12.setText("nameLabel12");

        spaceLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel12.setText("jLabel46");

        priceLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel12.setText("jLabel47");

        ownerLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel12.setText("jLabel48");

        javax.swing.GroupLayout slot12PanelLayout = new javax.swing.GroupLayout(slot12Panel);
        slot12Panel.setLayout(slot12PanelLayout);
        slot12PanelLayout.setHorizontalGroup(
            slot12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot12PanelLayout.setVerticalGroup(
            slot12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot12PanelLayout.createSequentialGroup()
                .addComponent(nameLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot12Panel, gridBagConstraints);

        slot11Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel11.setText("nameLabel11");

        spaceLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel11.setText("jLabel42");

        priceLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel11.setText("jLabel43");

        ownerLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel11.setText("jLabel44");

        javax.swing.GroupLayout slot11PanelLayout = new javax.swing.GroupLayout(slot11Panel);
        slot11Panel.setLayout(slot11PanelLayout);
        slot11PanelLayout.setHorizontalGroup(
            slot11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot11PanelLayout.setVerticalGroup(
            slot11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot11PanelLayout.createSequentialGroup()
                .addComponent(nameLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel11)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot11Panel, gridBagConstraints);

        slot16Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel16.setText("nameLabel16");

        spaceLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel16.setText("jLabel62");

        priceLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel16.setText("jLabel63");

        ownerLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel16.setText("jLabel64");

        javax.swing.GroupLayout slot16PanelLayout = new javax.swing.GroupLayout(slot16Panel);
        slot16Panel.setLayout(slot16PanelLayout);
        slot16PanelLayout.setHorizontalGroup(
            slot16PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot16PanelLayout.setVerticalGroup(
            slot16PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot16PanelLayout.createSequentialGroup()
                .addComponent(nameLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel16)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot16Panel, gridBagConstraints);

        slot2Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel2.setText("nameLabel2");

        spaceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel2.setText("jLabel6");

        priceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel2.setText("jLabel7");

        ownerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel2.setText("jLabel8");

        javax.swing.GroupLayout slot2PanelLayout = new javax.swing.GroupLayout(slot2Panel);
        slot2Panel.setLayout(slot2PanelLayout);
        slot2PanelLayout.setHorizontalGroup(
            slot2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot2PanelLayout.setVerticalGroup(
            slot2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot2PanelLayout.createSequentialGroup()
                .addComponent(nameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot2Panel, gridBagConstraints);

        slot14Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel14.setText("nameLabel14");

        spaceLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel14.setText("jLabel54");

        priceLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel14.setText("jLabel55");

        ownerLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel14.setText("jLabel56");

        javax.swing.GroupLayout slot14PanelLayout = new javax.swing.GroupLayout(slot14Panel);
        slot14Panel.setLayout(slot14PanelLayout);
        slot14PanelLayout.setHorizontalGroup(
            slot14PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot14PanelLayout.setVerticalGroup(
            slot14PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot14PanelLayout.createSequentialGroup()
                .addComponent(nameLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel14)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot14Panel, gridBagConstraints);

        slot15Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel15.setText("nameLabel15");

        spaceLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel15.setText("jLabel58");

        priceLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel15.setText("jLabel59");

        ownerLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel15.setText("jLabel60");

        javax.swing.GroupLayout slot15PanelLayout = new javax.swing.GroupLayout(slot15Panel);
        slot15Panel.setLayout(slot15PanelLayout);
        slot15PanelLayout.setHorizontalGroup(
            slot15PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot15PanelLayout.setVerticalGroup(
            slot15PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot15PanelLayout.createSequentialGroup()
                .addComponent(nameLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownerLabel15)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        jPanel24.add(slot15Panel, gridBagConstraints);

        slot3Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel3.setText("nameLabel3");

        spaceLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel3.setText("jLabel10");

        priceLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel3.setText("jLabel11");

        ownerLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel3.setText("jLabel12");

        javax.swing.GroupLayout slot3PanelLayout = new javax.swing.GroupLayout(slot3Panel);
        slot3Panel.setLayout(slot3PanelLayout);
        slot3PanelLayout.setHorizontalGroup(
            slot3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spaceLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(priceLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot3PanelLayout.setVerticalGroup(
            slot3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot3PanelLayout.createSequentialGroup()
                .addComponent(nameLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot3Panel, gridBagConstraints);

        slot4Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel4.setText("nameLabel4");

        spaceLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel4.setText("jLabel14");

        priceLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel4.setText("jLabel15");

        ownerLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel4.setText("jLabel16");

        javax.swing.GroupLayout slot4PanelLayout = new javax.swing.GroupLayout(slot4Panel);
        slot4Panel.setLayout(slot4PanelLayout);
        slot4PanelLayout.setHorizontalGroup(
            slot4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spaceLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(priceLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot4PanelLayout.setVerticalGroup(
            slot4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot4PanelLayout.createSequentialGroup()
                .addComponent(nameLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot4Panel, gridBagConstraints);

        slot5Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel5.setText("nameLabel5");

        spaceLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel5.setText("jLabel18");

        priceLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel5.setText("jLabel19");

        ownerLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel5.setText("jLabel20");

        javax.swing.GroupLayout slot5PanelLayout = new javax.swing.GroupLayout(slot5Panel);
        slot5Panel.setLayout(slot5PanelLayout);
        slot5PanelLayout.setHorizontalGroup(
            slot5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot5PanelLayout.setVerticalGroup(
            slot5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot5PanelLayout.createSequentialGroup()
                .addComponent(nameLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(priceLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel5)
                .addGap(24, 24, 24))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot5Panel, gridBagConstraints);

        slot6Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel6.setText("nameLabel6");

        spaceLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel6.setText("jLabel22");

        priceLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel6.setText("jLabel23");

        ownerLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel6.setText("jLabel24");

        javax.swing.GroupLayout slot6PanelLayout = new javax.swing.GroupLayout(slot6Panel);
        slot6Panel.setLayout(slot6PanelLayout);
        slot6PanelLayout.setHorizontalGroup(
            slot6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot6PanelLayout.setVerticalGroup(
            slot6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot6PanelLayout.createSequentialGroup()
                .addComponent(nameLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot6Panel, gridBagConstraints);

        slot7Panel.setPreferredSize(new java.awt.Dimension(100, 100));

        nameLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel7.setText("nameLabel7");

        spaceLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceLabel7.setText("jLabel26");

        priceLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel7.setText("jLabel27");

        ownerLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLabel7.setText("jLabel28");

        javax.swing.GroupLayout slot7PanelLayout = new javax.swing.GroupLayout(slot7Panel);
        slot7Panel.setLayout(slot7PanelLayout);
        slot7PanelLayout.setHorizontalGroup(
            slot7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(spaceLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ownerLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slot7PanelLayout.setVerticalGroup(
            slot7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot7PanelLayout.createSequentialGroup()
                .addComponent(nameLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spaceLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        jPanel24.add(slot7Panel, gridBagConstraints);

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        tabbedPane.addTab("game board", gamePanel);

        javax.swing.GroupLayout testingPanelLayout = new javax.swing.GroupLayout(testingPanel);
        testingPanel.setLayout(testingPanelLayout);
        testingPanelLayout.setHorizontalGroup(
            testingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        testingPanelLayout.setVerticalGroup(
            testingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        tabbedPane.addTab("testing panel", testingPanel);

        menu.setText("Setting");

        menuItem1.setText("jMenuItem1");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        menu.add(menuItem1);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItem1;
    private javax.swing.JLabel nameLabel0;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel10;
    private javax.swing.JLabel nameLabel11;
    private javax.swing.JLabel nameLabel12;
    private javax.swing.JLabel nameLabel13;
    private javax.swing.JLabel nameLabel14;
    private javax.swing.JLabel nameLabel15;
    private javax.swing.JLabel nameLabel16;
    private javax.swing.JLabel nameLabel17;
    private javax.swing.JLabel nameLabel18;
    private javax.swing.JLabel nameLabel19;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel20;
    private javax.swing.JLabel nameLabel21;
    private javax.swing.JLabel nameLabel22;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JLabel nameLabel7;
    private javax.swing.JLabel nameLabel8;
    private javax.swing.JLabel nameLabel9;
    private javax.swing.JLabel ownerLabel0;
    private javax.swing.JLabel ownerLabel1;
    private javax.swing.JLabel ownerLabel10;
    private javax.swing.JLabel ownerLabel11;
    private javax.swing.JLabel ownerLabel12;
    private javax.swing.JLabel ownerLabel13;
    private javax.swing.JLabel ownerLabel14;
    private javax.swing.JLabel ownerLabel15;
    private javax.swing.JLabel ownerLabel16;
    private javax.swing.JLabel ownerLabel17;
    private javax.swing.JLabel ownerLabel18;
    private javax.swing.JLabel ownerLabel19;
    private javax.swing.JLabel ownerLabel2;
    private javax.swing.JLabel ownerLabel20;
    private javax.swing.JLabel ownerLabel21;
    private javax.swing.JLabel ownerLabel22;
    private javax.swing.JLabel ownerLabel3;
    private javax.swing.JLabel ownerLabel4;
    private javax.swing.JLabel ownerLabel5;
    private javax.swing.JLabel ownerLabel6;
    private javax.swing.JLabel ownerLabel7;
    private javax.swing.JLabel ownerLabel8;
    private javax.swing.JLabel ownerLabel9;
    private javax.swing.JLabel priceLabel0;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel10;
    private javax.swing.JLabel priceLabel11;
    private javax.swing.JLabel priceLabel12;
    private javax.swing.JLabel priceLabel13;
    private javax.swing.JLabel priceLabel14;
    private javax.swing.JLabel priceLabel15;
    private javax.swing.JLabel priceLabel16;
    private javax.swing.JLabel priceLabel17;
    private javax.swing.JLabel priceLabel18;
    private javax.swing.JLabel priceLabel19;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel20;
    private javax.swing.JLabel priceLabel21;
    private javax.swing.JLabel priceLabel22;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel priceLabel5;
    private javax.swing.JLabel priceLabel6;
    private javax.swing.JLabel priceLabel7;
    private javax.swing.JLabel priceLabel8;
    private javax.swing.JLabel priceLabel9;
    private javax.swing.JPanel slot0Panel;
    private javax.swing.JPanel slot10Panel;
    private javax.swing.JPanel slot11Panel;
    private javax.swing.JPanel slot12Panel;
    private javax.swing.JPanel slot13Panel;
    private javax.swing.JPanel slot14Panel;
    private javax.swing.JPanel slot15Panel;
    private javax.swing.JPanel slot16Panel;
    private javax.swing.JPanel slot17Panel;
    private javax.swing.JPanel slot18Panel;
    private javax.swing.JPanel slot19Panel;
    private javax.swing.JPanel slot1Panel;
    private javax.swing.JPanel slot20Panel;
    private javax.swing.JPanel slot21Panel;
    private javax.swing.JPanel slot22Panel;
    private javax.swing.JPanel slot2Panel;
    private javax.swing.JPanel slot3Panel;
    private javax.swing.JPanel slot4Panel;
    private javax.swing.JPanel slot5Panel;
    private javax.swing.JPanel slot6Panel;
    private javax.swing.JPanel slot7Panel;
    private javax.swing.JPanel slot8Panel;
    private javax.swing.JPanel slot9Panel;
    private javax.swing.JLabel spaceLabel0;
    private javax.swing.JLabel spaceLabel1;
    private javax.swing.JLabel spaceLabel10;
    private javax.swing.JLabel spaceLabel11;
    private javax.swing.JLabel spaceLabel12;
    private javax.swing.JLabel spaceLabel13;
    private javax.swing.JLabel spaceLabel14;
    private javax.swing.JLabel spaceLabel15;
    private javax.swing.JLabel spaceLabel16;
    private javax.swing.JLabel spaceLabel17;
    private javax.swing.JLabel spaceLabel18;
    private javax.swing.JLabel spaceLabel19;
    private javax.swing.JLabel spaceLabel2;
    private javax.swing.JLabel spaceLabel20;
    private javax.swing.JLabel spaceLabel21;
    private javax.swing.JLabel spaceLabel22;
    private javax.swing.JLabel spaceLabel3;
    private javax.swing.JLabel spaceLabel4;
    private javax.swing.JLabel spaceLabel5;
    private javax.swing.JLabel spaceLabel6;
    private javax.swing.JLabel spaceLabel7;
    private javax.swing.JLabel spaceLabel8;
    private javax.swing.JLabel spaceLabel9;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel testingPanel;
    // End of variables declaration//GEN-END:variables
}
